version: '3.6'
services :
    postgres:
        network_mode: host
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
