version: '3.6'
services :
    postgres:
        network_mode: host
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
          - dados:/data/db
volumes: 
  dados: 